#%RAML 1.0
types:
  DefaultPayload_3745a9d2f54382cb2bc3c576d019a471:
    type: any
  DefaultPayload_1f4b570557c77ad06f37653b2a1ffa4d:
    type: any
  Entity17:
    type: Entity18
  Entity18:
    type: "!include data_model_f8d6a2a1c5ce210c05f974b90aab7340.raml | !include data_model_9f4366e043b8a1f37f39ba06d291f9dc.raml"
title: covid-data-tracking-api.raml
/covid19/v1:
  get:
    displayName: Custom
    responses:
      "200":
        body:
          application/json: DefaultPayload_3745a9d2f54382cb2bc3c576d019a471
/covid19/v1/cases:
  get:
    displayName: Custom
    responses:
      "200":
        body:
          application/json: DefaultPayload_1f4b570557c77ad06f37653b2a1ffa4d
/covid19/v1/high-level-policy:
  get:
    displayName: Custom
    queryParameters:
      country:
        description: ISO 3-letter code for country
        type: string
      state?:
        description: Provide 2 letter US State code
        type: string
    responses:
      "200":
        body:
          application/json: Entity17
/covid19/v1/locations:
  get:
    displayName: Custom
    queryParameters:
      zipCode:
        description: Use ZIP Code as query parameter
        type: string
    responses:
      "200":
        body:
          application/json: "!include data_model_ae17e04fa8cb412f63986bcdfbc46962.raml"
/covid19/v1/cases/covidTracking:
  get:
    displayName: Custom
    queryParameters:
      state:
        description: Provide 2 letter US State code
        type: string
      daysInPast:
        description: How many days of data to fetch?
        type: integer
    responses:
      "200":
        body:
          application/json: "!include data_model_23076dd6c742c730c3fd4856a5196d96.raml"
/covid19/v1/cases/eucdc:
  get:
    displayName: Custom
    queryParameters:
      country:
        description: ISO 2-letter code for country
        type: string
      daysInPast:
        description: How many days of data to fetch?
        type: integer
    responses:
      "200":
        body:
          application/json: "!include data_model_6dea653e79a9fb95e385728872eab66b.raml"
/covid19/v1/cases/newYorkTimes:
  get:
    displayName: Custom
    queryParameters:
      zipCode:
        description: Use ZIP Code as query parameter
        type: string
      daysInPast:
        description: How many days of data to fetch?
        type: integer
    responses:
      "200":
        body:
          application/json: "!include data_model_b2b9720720e7b5f53944a521b71e59d5.raml"
