#%RAML 1.0 DataType
properties:
  leftTopLatLong:
    type: number
    format: float
  rightTopLatLong:
    type: number
    format: float
  leftBottomLatLong:
    type: number
    format: float
  rightBottomLatLong:
    type: number
    format: float
