#%RAML 1.0 DataType
properties:
  date:
    type: date-only
  reportedCt:
    type: number
    format: float
  deathCt:
    type: number
    format: float
  recoveredCt:
    type: number
    format: float
  activeCaseCt:
    type: number
    format: float
  peoplePositiveCasesCt:
    type: number
    format: float
  peoplePositiveNewCasesCt:
    type: number
    format: float
  peopleNegativeCasesCt:
    type: number
    format: float
  peopleNegativeNewCt:
    type: number
    format: float
  peoplePendingCasesCt:
    type: number
    format: float
  peopleDeathNewCt:
    type: number
    format: float
  peopleHospCurrentlyCt:
    type: number
    format: float
  peopleHospNewCt:
    type: number
    format: float
  peopleHospCumlCt:
    type: number
    format: float
  peopleInIntnsvCareCurrCt:
    type: number
    format: float
  peopleInIntnsvCareCumlCt:
    type: number
    format: float
  peopleIntubatedCurrentlyCt:
    type: number
    format: float
  peopleIntubatedCumulativeCt:
    type: number
    format: float
