#%RAML 1.0
types:
  DefaultPayload_eecc24faf5d4a6b6747a4191bf1f97b2:
    type: any
  DefaultPayload_5f1238d04f393c71744a4966629a09f1:
    type: any
  Entity8:
    description: |
      The request body can be easily created in JavaScript using FormData:

      ```
      let data = new FormData();
      data.append('aid', aid); // anonymousId
      data.append('tz', d.getTimezoneOffset()); //timezone
      ```
      and then passed to XHR or Fetch function as a parameter:
      ```
      fetch(url, {
        method: 'POST',
        body: data
      });
      ```
    properties:
      aid:
        type: string
      tz:
        type: integer
  DefaultPayload_ab9532891c0aea6cdad10750edce3249:
    type: any
  DefaultPayload_e91a6f576d145b6f8fc770a13134523f:
    type: any
  DefaultPayload_ae245954f12742778423aaf52786d14d:
    type: any
title: api.raml
/analyzer:
  get:
    displayName: Custom
    responses:
      "200":
        body:
          application/json: DefaultPayload_ab9532891c0aea6cdad10750edce3249
/tasks:
  get:
    displayName: Custom
    responses:
      "200":
        body:
          application/json: DefaultPayload_e91a6f576d145b6f8fc770a13134523f
/analytics/query:
  get:
    displayName: Custom
    responses:
      "200":
        body:
          application/json: DefaultPayload_5f1238d04f393c71744a4966629a09f1
/analytics/record:
  post:
    displayName: Custom
    body: Entity8
/analytics/query/daily:
  get:
    displayName: Custom
    responses:
      "200":
        body:
          application/json: DefaultPayload_eecc24faf5d4a6b6747a4191bf1f97b2
/analytics/query/{scope}:
  get:
    displayName: Custom
    responses:
      "200":
        body:
          application/json: DefaultPayload_ae245954f12742778423aaf52786d14d
  uriParameters:
    scope:
      description: |
        A time period for the statistics. Only `weekly` and `monthly` values are allowed.
      type: string
/tasks/{scope}/{type}:
  get:
    displayName: Custom
    responses:
      "200":
        body:
          application/json: DefaultPayload_e91a6f576d145b6f8fc770a13134523f
  uriParameters:
    type:
      description: |
        Type of the data to compute. Can be either `users` to compute number of users for given scope and `sessions` to compute number of sessions.
      type: string
    scope:
      description: |
        The time scope of computation to perform. It can be either `daily`, `weekly` or `monthly`.

        Except for the daily type, actual start date may be different than the one provided in the `day` query parameter.
        For weekly computations the server will always set monday going backward if the day is not Monday.
        Similar for monthly computations it will be always set to the first day of month.
      type: string
/.well-known//acme-challenge/{challenge}:
  get:
    displayName: Custom
    responses:
      "200":
        body:
          text/html:
            type: string
  uriParameters:
    challenge:
      description: A challenge code
      type: string
