#%RAML 1.0 Library
types:
  StoreInfo:
    description: Information about store
    properties:
      storeId:
        type: string
      name:
        type: string
      description:
        type: string
      notes:
        type: string
      openingHours:
        type: string
      distance:
        type: number
        format: float
      distanceUnit:
        type: string
  ContactInfo:
    properties:
      email:
        type: string
      phone:
        type: string
  Geo:
    description: Geographic coordinates of store
    properties:
      latitude:
        type: number
        format: float
      longitude:
        type: number
        format: float
