#%RAML 1.0
types:
  Entity2:
    properties:
      receiver:
        type: string
      body:
        type: string
      important:
        type: boolean
  DefaultPayload_bb961dd02c47c983a4fca3b1c62547de:
    type: any
  Entity9:
    type: example-types_raml.Org
    properties:
      id:
        type: string
  Entity11:
    type: example-types_raml.Org
    properties:
      id:
        type: string
uses:
  example-types_raml: data_model_44fc06a6d6922038caee6ea4fb1eb095.raml
title: api.raml
/messages:
  get:
    displayName: Custom
    queryParameters:
      until:
        description: Date right limit of the messages query.
        type: date-only
      since:
        description: Date left limit of the messages query.
        type: date-only
    responses:
      "200":
        body:
          application/json:
            items: "!include data_model_ed72f421fa574b1aadf227d48e3f68e2.raml"
  post:
    displayName: Custom
    body: Entity2
/orgs:
  get:
    displayName: Custom
    responses:
      "200":
        body:
          application/json: DefaultPayload_bb961dd02c47c983a4fca3b1c62547de
/people:
  post:
    displayName: Custom
    body: "!include data_model_59c1f096d95dd2f4b0bffdd159a36c27.raml"
  get:
    displayName: Custom
/products:
  post:
    displayName: Custom
    body: "!include data_model_b89ca2c6a4ca5b36a5963c915028b77d.raml"
    responses:
      "200":
        body:
          application/json: "!include data_model_b89ca2c6a4ca5b36a5963c915028b77d.raml"
  get:
    displayName: Custom
/messages/bulk:
  post:
    displayName: Custom
    body:
      items: "!include data_model_de473bb7362625ed509703d5ab46d4bf.raml"
/orgs/{orgId}:
  get:
    displayName: Custom
    responses:
      "200":
        body:
          application/json: Entity9
  put:
    displayName: Custom
    body: Entity11
    responses:
      "200":
        body:
          application/json: example-types_raml.Org
  uriParameters:
    orgId:
      type: string
/people/{personId}:
  get:
    displayName: Custom
    responses:
      "200":
        body:
          application/json: "!include data_model_59c1f096d95dd2f4b0bffdd159a36c27.raml"
  delete:
    displayName: Custom
  put:
    displayName: Custom
    body: "!include data_model_59c1f096d95dd2f4b0bffdd159a36c27.raml"
  uriParameters:
    personId:
      description: The ID of the person in the system. It is generated by the database numeric value for the person.
      type: integer
/products/{productId}:
  get:
    displayName: Custom
    responses:
      "200":
        body:
          application/json: "!include data_model_b89ca2c6a4ca5b36a5963c915028b77d.raml"
  uriParameters:
    productId:
      type: string
/orgs/{orgId}/managers:
  get:
    displayName: Custom
    responses:
      "200":
        body:
          application/json:
            items: example-types_raml.Manager
