#%RAML 1.0 Library
types:
  MerchantsCommonComponentsSpecification-v1-schema-shipping_options_request-json:
    description: Includes options presented by the payee/merchant to the payer to ship or pick up their item(s). Also includes the shipping options elected by the payer.
    properties:
      id:
        type: string
      label:
        type: string
      attribute1:
        type: string
      amount: amount
  seller_protection:
    type: MerchantsCommonComponentsSpecification-v1-schema-seller_protection-json
    properties: {}
  "":
    type: any
  MerchantsCommonComponentsSpecification-v1-schema-authorization-json:
    description: The authorized payment transaction.
    type:
      - MerchantsCommonComponentsSpecification-v1-schema-authorization_status-json
      - MerchantsCommonComponentsSpecification-v1-schema-activity_timestamps-json
    properties:
      id:
        type: string
      invoice_id:
        type: string
      expiration_time:
        type: string
      amount: amount
  seller_payable_breakdown:
    description: The breakdown of the refund.
    properties:
      gross_amount: gross_amount
      paypal_fee: paypal_fee
      net_amount: net_amount
      platform_fees:
        items: items
      total_refunded_amount: total_refunded_amount
  name:
    description: The name of the person to whom to ship the items. Supports only the `full_name` property.
    type: MCCS-v1-schema-CC-v3-json-openapi-2-name-json
    properties: {}
  purchase_unit_request-json:
    description: The purchase unit request. Includes required information for the payment contract.
    properties:
      reference_id:
        type: string
      description:
        type: string
      custom_id:
        type: string
      invoice_id:
        type: string
      soft_descriptor:
        type: string
      amount: amount
      payee: payee
      payment_instruction: payment_instruction
      items:
        items: items
      shipping: shipping
  payment_instruction:
    type: MerchantsCommonComponentsSpecification-v1-schema-payment_instruction-json
  MerchantsCommonComponentsSpecification-v1-schema-refund-json:
    description: The refund information.
    type:
      - MerchantsCommonComponentsSpecification-v1-schema-refund_status-json
      - MerchantsCommonComponentsSpecification-v1-schema-activity_timestamps-json
    properties:
      id:
        type: string
      invoice_id:
        type: string
      note_to_payer:
        type: string
      amount: amount
      seller_payable_breakdown: seller_payable_breakdown
      links:
        items: items
  payer:
    type: MerchantsCommonComponentsSpecification-v1-schema-payer-json
  MerchantsCommonComponentsSpecification-v1-schema-exchange_rate-json:
    description: The exchange rate that determines the amount to convert from one currency to another currency.
    properties:
      source_currency:
        type: string
      target_currency:
        type: string
      value:
        type: string
  MCCS-v1-schema-CC-v3-json-openapi-2-name-json:
    description: The name of the party.
    properties:
      prefix:
        type: string
      given_name:
        type: string
      surname:
        type: string
      middle_name:
        type: string
      suffix:
        type: string
      alternate_full_name:
        type: string
      full_name:
        type: string
  item_total:
    description: The subtotal for all items. Required if the request includes `purchase_units[].items[].unit_amount`. Must equal the sum of `(items[].unit_amount * items[].quantity)` for all items.
    type: MCCS-v1-schema-CC-v3-json-openapi-2-money-json
    properties: {}
  billing_address:
    description: The billing address for this card. Supports only the `address_line_1`, `address_line_2`, `admin_area_1`, `admin_area_2`, `postal_code`, and `country_code` properties.
    type: MCCS-v1-schema-CC-v3-json-openapi-2-address_portable-json
    properties: {}
  MCCS-v1-schema-CC-v3-json-openapi-2-patch-json:
    description: The JSON patch object to apply partial updates to resources.
    properties:
      op:
        type: string
      path:
        type: string
      from:
        type: string
      value: value
  MerchantsCommonComponentsSpecification-v1-schema-payment_method-json:
    description: The customer and merchant payment preferences.
    properties:
      payer_selected:
        type: string
      payee_preferred:
        type: string
  insurance:
    description: The insurance fee for all items within a given `purchase_unit`.
    type: MCCS-v1-schema-CC-v3-json-openapi-2-money-json
    properties: {}
  MCCS-v1-schema-CC-v3-json-openapi-2-phone-json:
    description: The phone number, in its canonical international [E.164 numbering plan format](https://www.itu.int/rec/T-REC-E.164/en).
    properties:
      country_code:
        type: string
      national_number:
        type: string
      extension_number:
        type: string
  tax:
    description: The item tax for each unit. If <code>tax</code> is specified, <code>purchase_units[].amount.breakdown.tax_total</code> is required. Must equal <code>tax * quantity</code> for all items.
    type: MCCS-v1-schema-CC-v3-json-openapi-2-money-json
    properties: {}
  MerchantsCommonComponentsSpecification-v1-schema-amount_with_breakdown-json:
    description: The total order amount with an optional breakdown that provides details, such as the total item amount, total tax amount, shipping, handling, insurance, and discounts, if any.<br/>If you specify `amount.breakdown`, the amount equals `item_total` plus `tax_total` plus `shipping` plus `handling` plus `insurance` minus `shipping_discount`.<br/>The amount must be a positive number. For listed of supported currencies and decimal precision, see the PayPal REST APIs <a href="/docs/integration/direct/rest/currency-codes/">Currency Codes</a>.
    type: MCCS-v1-schema-CC-v3-json-openapi-2-money-json
    properties: {}
  MerchantsCommonComponentsSpecification-v1-schema-authorization_status-json:
    description: The status fields for an authorized payment.
    properties:
      status:
        type: string
  tax_total:
    description: The total tax for all items. Required if the request includes `purchase_units.items.tax`. Must equal the sum of `(items[].tax * items[].quantity)` for all items.
    type: MCCS-v1-schema-CC-v3-json-openapi-2-money-json
    properties: {}
  handling:
    description: The handling fee for all items within a given `purchase_unit`.
    type: MCCS-v1-schema-CC-v3-json-openapi-2-money-json
    properties: {}
  gross_amount:
    description: The amount for this captured payment.
    type: MCCS-v1-schema-CC-v3-json-openapi-2-money-json
    properties: {}
  MCCS-v1-schema-CC-v3-json-openapi-2-error_details-json:
    description: The error details. Required for client-side `4XX` errors.
    properties:
      field:
        type: string
      value:
        type: string
      location:
        type: string
      issue:
        type: string
      description:
        type: string
  MCCS-v1-schema-CC-v3-json-openapi-2-address_portable-json:
    description: "The portable international postal address. Maps to [AddressValidationMetadata](https://github.com/googlei18n/libaddressinput/wiki/AddressValidationMetadata) and HTML 5.1 [Autofilling form controls: the autocomplete attribute](https://www.w3.org/TR/html51/sec-forms.html#autofilling-form-controls-the-autocomplete-attribute)."
    properties:
      address_line_1:
        type: string
      address_line_2:
        type: string
      address_line_3:
        type: string
      admin_area_4:
        type: string
      admin_area_3:
        type: string
      admin_area_2:
        type: string
      admin_area_1:
        type: string
      postal_code:
        type: string
      address_details: address_details
  patternProperties:
    description: The pattern properties.
    type: any
  items:
    type: MCCS-v1-schema-CC-v3-json-openapi-2-link_description-json
    properties: {}
  additionalItems:
    description: Any additional items.
    type: any
  order-json:
    description: The order details.
    type: MerchantsCommonComponentsSpecification-v1-schema-activity_timestamps-json
  MerchantsCommonComponentsSpecification-v1-schema-card-json:
    description: The payment card to use to fund a payment. Can be a credit or debit card.
    properties:
      id:
        type: string
      name:
        type: string
      number:
        type: string
      security_code:
        type: string
      last_digits:
        type: string
      billing_address: billing_address
  MerchantsCommonComponentsSpecification-v1-schema-payment_source-json:
    description: The payment source definition.
    type: any
  application_context-json:
    description: Customizes the payer experience during the approval process for the payment with PayPal.<blockquote><strong>Note:</strong> Partners and Marketplaces might have <code>brand_name</code> and <code>shipping_preference</code> configured during partner account setup that will override the request values.</blockquote>
    properties:
      brand_name:
        type: string
      landing_page:
        type: string
      shipping_preference:
        type: string
      user_action:
        type: string
      return_url:
        type: string
      cancel_url:
        type: string
      payment_token:
        type: string
  payable_amount:
    description: The net amount debited from the merchant's PayPal account.
    type: MCCS-v1-schema-CC-v3-json-openapi-2-money-json
    properties: {}
  amount:
    description: The amount for this captured payment.
    type: MCCS-v1-schema-CC-v3-json-openapi-2-money-json
    properties: {}
  purchase_unit-json:
    description: The purchase unit details. Used to capture required information for the payment contract.
    properties:
      reference_id:
        type: string
      description:
        type: string
      custom_id:
        type: string
      invoice_id:
        type: string
      id:
        type: string
      soft_descriptor:
        type: string
  MerchantsCommonComponentsSpecification-v1-schema-payee_base-json:
    description: The details for the merchant who receives the funds and fulfills the order. The merchant is also known as the payee.
    properties:
      email_address:
        type: string
      merchant_id:
        type: string
      client_id:
        type: string
  receivable_amount:
    description: The net amount that is credited to the payee's PayPal account. Returned only when the currency of the captured payment is different from the currency of the PayPal account where the payee wants to credit the funds. The amount is computed as <code>net_amount</code> times <code>exchange_rate</code>.
    type: MCCS-v1-schema-CC-v3-json-openapi-2-money-json
    properties: {}
  MerchantsCommonComponentsSpecification-v1-schema-payee_displayable-json:
    description: The merchant information. The merchant is also known as the payee. Appears to the customer in checkout, transactions, email receipts, and transaction history.
    properties:
      business_email:
        type: string
      brand_name:
        type: string
      business_phone: business_phone
  status_details:
    description: The details of the captured payment status.
    properties:
      reason:
        type: string
  authorize_request-json:
    description: Authorize an order.
    type: order_action_request-json
  properties:
    type: any
  MerchantsCommonComponentsSpecification-v1-schema-item-json:
    description: The details for the items to be purchased.
    properties:
      name:
        type: string
      quantity:
        type: string
      description:
        type: string
      sku:
        type: string
      category:
        type: string
      unit_amount: unit_amount
      tax: tax
  address_details:
    description: The non-portable additional address details that are sometimes needed for compliance, risk, or other scenarios where fine-grain address information might be needed. Not portable with common third party and opensource. Redundant with core fields. For example, `address_portable.address_line_1` is usually a combination of `address_details.street_number` and `street_name` and `street_type`.
    properties:
      street_number:
        type: string
      street_name:
        type: string
      street_type:
        type: string
      delivery_service:
        type: string
      building_name:
        type: string
      sub_building:
        type: string
  seller_receivable_breakdown:
    description: The detailed breakdown of the captured payment.
    properties:
      gross_amount: gross_amount
      paypal_fee: paypal_fee
      net_amount: net_amount
      receivable_amount: receivable_amount
      platform_fees:
        items: items
  MerchantsCommonComponentsSpecification-v1-schema-refund_status-json:
    description: The refund status.
    properties:
      status:
        type: string
      status_details: status_details
  payment_collection-json:
    description: The collection of payments, or transactions, for a purchase unit in an order. For example, authorized payments, captured payments, and refunds.
    type: any
  paypal_fee:
    description: The applicable fee for this captured payment.
    type: MCCS-v1-schema-CC-v3-json-openapi-2-money-json
    properties: {}
  MCCS-v1-schema-CC-v3-json-openapi-2-link_schema-json:
    description: The request data or link target.
    properties:
      fragmentResolution:
        type: string
      pathStart:
        type: string
      additionalItems: additionalItems
      dependencies: dependencies
      items: items
      definitions: definitions
      patternProperties: patternProperties
      properties: properties
      allOf:
        items: items
      anyOf:
        items: items
      oneOf:
        items: items
      not: not
      links:
        items: items
      media: media
  MerchantsCommonComponentsSpecification-v1-schema-platform_fee-json:
    description: The platform or partner fee, commission, or brokerage fee that is associated with the transaction. Not a separate or isolated transaction leg from the external perspective. The platform fee is limited in scope and is always associated with the original payment for the purchase unit.
    properties:
      amount: amount
      payee: payee
  not:
    type: any
  MerchantsCommonComponentsSpecification-v1-schema-payee-json:
    description: The merchant who receives the funds and fulfills the order. The merchant is also known as the payee.
    type: MerchantsCommonComponentsSpecification-v1-schema-payee_base-json
    properties: {}
  media:
    description: The media type and context-encoding scheme.
    properties:
      attribute2:
        type: string
      binaryEncoding:
        type: string
  net_amount:
    description: The net amount that the payee receives for this captured payment in their PayPal account. The net amount is computed as <code>gross_amount</code> minus the <code>paypal_fee</code> minus the <code>platform_fees</code>.
    type: MCCS-v1-schema-CC-v3-json-openapi-2-money-json
    properties: {}
  MerchantsCommonComponentsSpecification-v1-schema-token-json:
    description: The tokenized payment source to fund a payment.
    properties:
      id:
        type: string
      attribute3:
        type: string
  address:
    description: The address of the person to whom to ship the items Supports only the `address_line_1`, `address_line_2`, `admin_area_1`, `admin_area_2`, `postal_code`, and `country_code` properties.
    type: MCCS-v1-schema-CC-v3-json-openapi-2-address_portable-json
    properties: {}
  MCCS-v1-schema-CC-v3-json-openapi-2-link_description-json:
    description: The request-related [HATEOAS link](/docs/api/overview/#hateoas-links) information.
    properties:
      href:
        type: string
      rel:
        type: string
      method:
        type: string
      title:
        type: string
      mediaType:
        type: string
      encType:
        type: string
  order_action_request-json:
    description: Completes an action for an order.
    type: any
  MerchantsCommonComponentsSpecification-v1-schema-shipping_detail-json:
    description: The shipping details.
    properties:
      name: name
      address: address
  definitions:
    type: any
  MerchantsCommonComponentsSpecification-v1-schema-net_amount_breakdown_item-json:
    description: The net amount. Returned when the currency of the refund is different from the currency of the PayPal account where the merchant holds their funds.
    properties:
      payable_amount: payable_amount
      converted_amount: converted_amount
      exchange_rate: exchange_rate
  shipping_discount:
    description: The shipping discount for all items within a given `purchase_unit`.
    type: MCCS-v1-schema-CC-v3-json-openapi-2-money-json
    properties: {}
  converted_amount:
    description: The converted payable amount.
    type: MCCS-v1-schema-CC-v3-json-openapi-2-money-json
    properties: {}
  MerchantsCommonComponentsSpecification-v1-schema-payment_instruction-json:
    description: Any additional payment instructions for PayPal for Partner customers. Enables features for partners and marketplaces, such as delayed disbursement and collection of a platform fee. Applies during order creation for captured payments or during capture of authorized payments.
    type: any
  MerchantsCommonComponentsSpecification-v1-schema-activity_timestamps-json:
    description: The date and time stamps that are common to authorized payment, captured payment, and refund transactions.
    type: any
  order_request-json:
    description: The order request details.
    properties:
      intent:
        type: string
      payer: payer
  exchange_rate:
    description: The exchange rate that determines the amount that was debited from the merchant's PayPal account.
    type: MerchantsCommonComponentsSpecification-v1-schema-exchange_rate-json
    properties: {}
  business_phone:
    description: The phone number of the merchant. Appears to the customer in checkout, payment transactions, email receipts, and transaction history.
    type: MCCS-v1-schema-CC-v3-json-openapi-2-phone-json
    properties: {}
  MerchantsCommonComponentsSpecification-v1-schema-phone_with_type-json:
    description: The phone information.
    type: any
  MerchantsCommonComponentsSpecification-v1-schema-capture_status-json:
    description: The status of a captured payment.
    properties:
      status:
        type: string
      status_details: status_details
  value:
    description: The value to apply. The `remove` operation does not require a value.
    type: any
  dependencies:
    type: any
  unit_amount:
    description: The item price or rate per unit. If you specify <code>unit_amount</code>, <code>purchase_units[].amount.breakdown.item_total</code> is required. Must equal <code>unit_amount * quantity</code> for all items.
    type: MCCS-v1-schema-CC-v3-json-openapi-2-money-json
    properties: {}
  MerchantsCommonComponentsSpecification-v1-schema-amount_breakdown-json:
    description: The breakdown of the amount. Breakdown provides details such as total item amount, total tax amount, shipping, handling, insurance, and discounts, if any.
    properties:
      item_total: item_total
      shipping: shipping
      handling: handling
      tax_total: tax_total
      insurance: insurance
      shipping_discount: shipping_discount
  MerchantsCommonComponentsSpecification-v1-schema-tax_info-json:
    description: The tax ID of the customer. The customer is also known as the payer. Both `tax_id` and `tax_id_type` are required.
    properties:
      tax_id:
        type: string
      tax_id_type:
        type: string
  MCCS-v1-schema-CC-v3-json-openapi-2-money-json:
    description: The currency and amount for a financial transaction, such as a balance or payment due.
    properties:
      value:
        type: string
  payee:
    description: The recipient of the fee for this transaction. If you omit this value, the default is the API caller.
    type: MerchantsCommonComponentsSpecification-v1-schema-payee_base-json
    properties: {}
  MCCS-v1-schema-CC-v3-json-openapi-2-error-json:
    description: The error details.
    properties:
      name:
        type: string
      message:
        type: string
      debug_id:
        type: string
      information_link:
        type: string
      links:
        items: items
  total_refunded_amount:
    description: The total amount refunded from the original capture to date. For example, if a payer makes a $100 purchase and was refunded $20 a week ago and was refunded $30 in this refund, the `gross_amount` is $30 for this refund and the `total_refunded_amount` is $50.
    type: MCCS-v1-schema-CC-v3-json-openapi-2-money-json
    properties: {}
  shipping:
    description: The shipping fee for all items within a given `purchase_unit`.
    type: MCCS-v1-schema-CC-v3-json-openapi-2-money-json
    properties: {}
  MerchantsCommonComponentsSpecification-v1-schema-seller_protection-json:
    description: The level of protection offered as defined by [PayPal Seller Protection for Merchants](https://www.paypal.com/us/webapps/mpp/security/seller-protection).
    properties:
      status:
        type: string
      dispute_categories:
        items:
          type: string
  MerchantsCommonComponentsSpecification-v1-schema-capture-json:
    description: A captured payment.
    type:
      - MerchantsCommonComponentsSpecification-v1-schema-capture_status-json
      - MerchantsCommonComponentsSpecification-v1-schema-activity_timestamps-json
    properties:
      id:
        type: string
      invoice_id:
        type: string
      final_capture:
        type: boolean
      disbursement_mode:
        type: string
      amount: amount
      seller_protection: seller_protection
      seller_receivable_breakdown: seller_receivable_breakdown
      links:
        items: items
  MerchantsCommonComponentsSpecification-v1-schema-payer-json:
    description: The customer who approves and pays for the order. The customer is also known as the payer.
    type: any
