#%RAML 1.0 Library
types:
  Property:
    properties:
      kind:
        type: string
      etag:
        type: string
      selfLink:
        type: string
      key:
        type: string
      visibility:
        type: string
      value:
        type: string
  PropertyList:
    properties:
      kind:
        type: string
      etag:
        type: string
      selfLink:
        type: string
      items:
        items: Property
