#%RAML 1.0 DataType
displayName: Labels
description: A group of labels for the file.
properties:
  starred:
    type: boolean
  hidden:
    type: boolean
  trashed:
    type: boolean
  restricted:
    type: boolean
  viewed:
    type: boolean
