#%RAML 1.0 Library
types:
  App:
    properties:
      kind:
        type: string
      id:
        type: string
      name:
        type: string
      objectType:
        type: string
      supportsCreate:
        type: boolean
      supportsImport:
        type: boolean
      installed:
        type: boolean
      authorized:
        type: boolean
      useByDefault:
        type: boolean
      productUrl:
        type: string
      productId:
        type: string
      primaryMimeTypes:
        items:
          type: string
      secondaryMimeTypes:
        items:
          type: string
      primaryFileExtensions:
        items:
          type: string
      secondaryFileExtensions:
        items:
          type: string
      shortDescription:
        type: string
      longDescription:
        type: string
      openUrlTemplate:
        type: string
      supportsMultiOpen:
        type: boolean
      supportsOfflineCreate:
        type: boolean
      hasDriveWideScope:
        type: boolean
      createUrl:
        type: string
      createInFolderTemplate:
        type: string
      icons:
        items: "!include data_model_50b4de92d3d542695483b09e8acea36e.raml"
  AppList:
    description: Resource returned by the API when requesting list of files.
    properties:
      kind:
        type: string
      etag:
        type: string
      selfLink:
        type: string
      defaultAppIds:
        items:
          type: string
      items:
        items: App
