#%RAML 1.0 DataType
properties:
  canAddChildren:
    type: boolean
  canComment:
    type: boolean
  canCopy:
    type: boolean
  canDelete:
    type: boolean
  canDownload:
    type: boolean
  canEdit:
    type: boolean
  canListChildren:
    type: boolean
  canMoveItemIntoTeamDrive:
    type: boolean
  canMoveTeamDriveItem:
    type: boolean
  canReadRevisions:
    type: boolean
  canReadTeamDrive:
    type: boolean
  canRemoveChildren:
    type: boolean
  canRename:
    type: boolean
  canShare:
    type: boolean
  canTrash:
    type: boolean
  canUntrash:
    type: boolean
