#%RAML 1.0 DataType
displayName: User
description: A representation of a user in Google Drive.
properties:
  kind:
    type: string
  displayName:
    type: string
  isAuthenticatedUser:
    type: boolean
  permissionId:
    type: string
  emailAddress:
    type: string
  picture: picture
