#%RAML 1.0 DataType
description: |
  Message sent by a user object. This represents a message in user's sent folder.
properties:
  email:
    type: string
  message:
    type: string
  timestamp:
    type: integer
  attachements:
    items:
      type: string
  important:
    type: boolean
