#%RAML 1.0 DataType
displayName: A product resource
description: A single product representing an item in the store.
type: "!include data_model_faedcc827ec83999ba610238218391d1.raml"
properties:
  id:
    type: string
  name:
    type: string
  quantity:
    type: number
    format: float
  unit:
    type: string
  upc:
    type: string
  available:
    type: boolean
