#%RAML 1.0 DataType
description: |
  An image object representing an image object strored in the file store.
  The image can be only included in the response. It has no effect if the Image appear in the
  request. Endpoint handles image creation on it's own and clients can't process images
  except of sending image data.
properties:
  url:
    type: string
  thumb:
    type: string
