#%RAML 1.0 Library
types:
  Version:
    displayName: Version
    description: |
      Information about module version
    properties:
      arc:
        type: string
      module:
        type: string
  Person response object:
    displayName: Person response object
    description: |
      The representation of a person entity that is returned by the API.
      Because of security and privacy protection this object contains as little as possible 
      information about a person.
    type: Person list response object
    properties:
      modulesCount:
        type: number
        format: float
      themesCount:
        type: number
        format: float
      github:
        type: string
      modules:
        items: Response Module
      themes:
        items: Response Module
  Person:
    displayName: Person
    properties:
      name:
        type: string
      website:
        type: string
  ModuleInfo:
    description: |
      This type is used in communication between ARC application and the server to informa the app
      about a module installed in the application.
    properties:
      version:
        type: string
      id:
        type: string
  Person list response object:
    displayName: Person list response object
    description: |
      The representation of a person entity that is returned by the API in a list.
      Because of security and privacy protection this object contains as little as possible 
      information about a person.
    properties:
      name:
        type: string
      website:
        type: string
      ref:
        type: string
  Module:
    displayName: Module
    description: Module is a base class for both ARC extensions or themes.
    properties:
      name:
        type: string
      description:
        type: string
      repo:
        type: string
      attribute1:
        type: string
      usage:
        type: string
      starredByUser:
        type: boolean
      version: Version
  Response Module:
    displayName: Response Module
    description: A module that is put into a response object
    type: Module
    properties:
      id:
        type: string
      created:
        type: datetime
      downloads:
        type: number
        format: float
      stars:
        type: number
        format: float
