#%RAML 1.0
types:
  schema10:
    type: any
uses:
  orders_v2_api-spec_raml: data_model_8870cff922f072518e04a11e214e0140.raml
title: orders_v2_api-spec.raml
/orders:
  post:
    displayName: Custom
    body: orders_v2_api-spec_raml.order_request-json
    responses:
      "201":
        body:
          application/json: orders_v2_api-spec_raml.order-json
/orders/{order_id}:
  get:
    displayName: Custom
    responses:
      "200":
        body:
          application/json: orders_v2_api-spec_raml.order-json
  patch:
    displayName: Custom
    body:
      items: schema10
  uriParameters:
    order_id:
      description: The ID of the order to update.
      type: string
/orders/{order_id}/authorize:
  post:
    displayName: Custom
    body: orders_v2_api-spec_raml.authorize_request-json
    responses:
      "200":
        body:
          application/json: orders_v2_api-spec_raml.order-json
/orders/{order_id}/capture:
  post:
    displayName: Custom
    body: orders_v2_api-spec_raml.order_action_request-json
    responses:
      "200":
        body:
          application/json: orders_v2_api-spec_raml.order-json
/orders/{order_id}/save:
  post:
    displayName: Custom
    responses:
      "200":
        body:
          application/json: orders_v2_api-spec_raml.order-json
/orders/{order_id}/validate-payment-method:
  post:
    displayName: Custom
    body: orders_v2_api-spec_raml.order_action_request-json
    responses:
      "200":
        body:
          application/json: orders_v2_api-spec_raml.order-json
/orders/{order_id}/void:
  post:
    displayName: Custom
    responses:
      "200":
        body:
          application/json: orders_v2_api-spec_raml.order-json
