#%RAML 1.0 Library
types:
  "":
    type: any
  AddressUnit:
    description: |
      address unit
    type: Entity1
  Quantity:
    description: |
      a quantity
    properties:
      quantityType:
        type: string
      amount:
        type: number
        format: float
      unit:
        type: string
  secondaryAddress?:
    type: any
  Location:
    description: |
      location
    properties:
      locationType:
        type: string
      deliveryMethod:
        type: string
      locationId: locationId
  MonetaryValue:
    description: |
      represents an amount in a given currency
    properties:
      name:
        type: string
      currency:
        type: string
      currencyValue:
        type: number
        format: float
  PostalAddress:
    description: |
      postal address of internal organization
    properties:
      identifier:
        type: string
      attribute2:
        type: string
      addressUnit:
        type: string
      mailStopCode: mailStopCode?
      attention: attention?
      recipient: recipient?
      address: address?
      secondaryAddress: secondaryAddress?
      city: city?
      state: state?
      postalCode: postalCode?
      country: country?
  state?:
    type: any
  prev?:
    description: |
      a link to the previous document in the series
    type: Link
    properties: {}
  Lifetime:
    description: |
      an object that has a finite lifespan. the object is considered
      to be valid at a point in time if:
      ```
      validFrom <= pointInTime < validUntil
      ```
    properties:
      validFrom:
        type: datetime
      validUntil:
        type: datetime
  ResponseMetadata:
    description: |
      a response metadata
    properties:
      messages:
        items: Message
  first?:
    description: |
      a link to the first document in the series
    type: Link
    properties: {}
  postalCode?:
    type: any
  self?:
    description: |
      conveys an identifier for the link's context.
    type: Link
    properties: {}
  HypermediaResponseMetadata:
    description: |
      hypermedia response metadata
    type: ResponseMetadata
    properties:
      messages:
        items: Message
  ContinuousQuantity:
    description: |
      continuous quantity
    type: Quantity
    properties:
      amount:
        type: number
        format: float
  CollectionPagingLinks:
    description: |
      collection of paging links
    type: Links
    properties:
      self: self?
      first: first?
      prev: prev?
      next: next?
      last: last?
  Links:
    description: |
      collection of hypermedia links
    properties:
      //: //
  attention?:
    type: any
  Price:
    description: |
      a price
    properties:
      salesUnit: SalesUnit
      amount: MonetaryValue
  SalesUnit:
    description: |
      sales unit
    properties:
      code:
        type: string
      name:
        type: string
  MeasurementSystem:
    description: |
      a standard that codifies a set of UnitOfMeasure, typically defined by a governmental
      or international agency.
    properties:
      code:
        type: string
      name:
        type: string
      description:
        type: string
  AddressUnitWithOptionalUnitNumber:
    description: |
      the unit address with optional unit number
    properties:
      unitType:
        type: string
      unitNumber:
        type: string
  last?:
    description: |
      a link to the last document in the series
    type: Link
    properties: {}
  next?:
    description: |
      a link to the next document in the series
    type: Link
    properties: {}
  mailStopCode?:
    type: any
  ErrorResponse:
    description: |
      error response
    type: DefaultResponse
    properties: {}
  locationId:
    type: any
  DiscreteQuantity:
    description: |
      discrete quantity
    type: Quantity
    properties:
      amount:
        type: integer
  DefaultResponse:
    description: |
      default response
    properties:
      _meta: _meta
  CollectionResponseMetadata:
    description: |
      collection of response messages
    type: ResponseMetadata
    properties:
      totalItems:
        type: integer
      offset:
        type: integer
      limit:
        type: integer
      sortBy:
        type: string
  address?:
    type: any
  country?:
    type: any
  Message:
    description: |
      a message object
    properties:
      severity:
        type: string
      code:
        type: string
      description:
        type: string
  CollectionResponse:
    description: |
      collection of response messages
    type: DefaultResponse
    properties:
      _meta: CollectionResponseMetadata
  //:
    type: Link
    properties: {}
  AddressUnitWithRequiredUnitNumber:
    description: |
      the unit address with required unit number
    properties:
      unitType:
        type: string
      unitNumber:
        type: string
  Entity1:
    type: AddressUnitWithRequiredUnitNumber | AddressUnitWithOptionalUnitNumber
  recipient?:
    type: any
  _meta:
    type: ResponseMetadata
    properties: {}
  city?:
    type: any
  HypermediaCollectionResponse:
    description: |
      hypermedia collection response
    type: DefaultResponse
    properties:
      _meta: ResponseMetadata
      _links: CollectionPagingLinks
  HypermediaMessage:
    description: |
      a hypermedia message
    type: Message
    properties:
      href: Link
  Link:
    description: |
      a hypermedia link
    properties:
      href:
        type: string
      title:
        type: string
  Measure:
    description: |
      a physical property that can be quantified with a numeric value
    properties:
      name:
        type: string
      description:
        type: string
