#%RAML 1.0 Library

types:

  Animal:
    description: not a plant, not a fungus
    properties:
      size: number
      birthDate: datetime

  Vegetable:
    description: Green organic matter
    properties:
      height: number