#%RAML 1.0
uses:
  payments_v2_api-spec_raml: data_model_a2f306e29b5e888075c0d3ddd7aa6498.raml
title: payments_v2_api-spec.raml
/authorizations/{authorization_id}:
  get:
    displayName: Custom
    responses:
      "200":
        body:
          application/json: payments_v2_api-spec_raml.MCCS-v1-schema-authorization_json
  uriParameters:
    authorization_id:
      description: The ID of the authorized payment for which to show details.
      type: string
/captures/{capture_id}:
  get:
    displayName: Custom
    responses:
      "200":
        body:
          application/json: payments_v2_api-spec_raml.MCCS-v1-schema-capture_json
  uriParameters:
    capture_id:
      description: The PayPal-generated ID for the captured payment for which to show details.
      type: string
/refunds/{refund_id}:
  get:
    displayName: Custom
    responses:
      "200":
        body:
          application/json: payments_v2_api-spec_raml.MCCS-v1-schema-refund_json
  uriParameters:
    refund_id:
      description: The PayPal-generated ID for the refund for which to show details.
      type: string
/authorizations/{authorization_id}/capture:
  post:
    displayName: Custom
    body: payments_v2_api-spec_raml.capture_request_json
    responses:
      "201":
        body:
          application/json: payments_v2_api-spec_raml.MCCS-v1-schema-capture_json
/authorizations/{authorization_id}/reauthorize:
  post:
    displayName: Custom
    body: payments_v2_api-spec_raml.reauthorize_request_json
    responses:
      "201":
        body:
          application/json: payments_v2_api-spec_raml.MCCS-v1-schema-authorization_json
/authorizations/{authorization_id}/void:
  post:
    displayName: Custom
/captures/{capture_id}/refund:
  post:
    displayName: Custom
    body: payments_v2_api-spec_raml.refund_request_json
    responses:
      "201":
        body:
          application/json: payments_v2_api-spec_raml.MCCS-v1-schema-refund_json
