#%RAML 1.0 Library
types:
  DailyUsers:
    description: An object representing response for daily users.
    type: DailyResult
    properties:
      kind:
        type: string
  AnalyticsRangeResult:
    properties:
      kind:
        type: string
      day:
        type: date-only
      result:
        type: integer
      items:
        items: DailyItemResult
  PeriodicalSessions:
    description: An object representing periodical (weekly or mothly) sessions data.
    type: AnalyticsRangeResult
    properties:
      kind:
        type: string
  PeriodicalUsers:
    description: An object representing periodical (weekly or mothly) users data.
    type: AnalyticsRangeResult
    properties:
      kind:
        type: string
  DailySessions:
    description: An object representing response for daily sessions.
    type: DailyResult
    properties:
      kind:
        type: string
  DailyResult:
    properties:
      kind:
        type: string
      result:
        type: integer
  DailyItemResult:
    description: |
      This object is returned in weekly and monthly analytics data.
      It is a representation of number of users or sessions for each day for the given time period.
    properties:
      day:
        type: date-only
      value:
        type: integer
