#%RAML 1.0 Library
types:
  Change:
    properties:
      kind:
        type: string
      id:
        type: string
      fileId:
        type: string
      selfLink:
        type: string
      deleted:
        type: boolean
      modificationDate:
        type: datetime
      attribute3:
        type: string
      teamDriveId:
        type: string
      file: file-lib_raml.DriveFile
      teamDrive: "!include data_model_f5b3d04a078ad6db60d2b09d6108e4da.raml"
  ChangeList:
    properties:
      kind:
        type: string
      etag:
        type: string
      selfLink:
        type: string
      nextPageToken:
        type: string
      nextLink:
        type: string
      largestChangeId:
        type: string
      items:
        items: Change
  Watch:
    properties:
      id:
        type: string
      expiration:
        type: string
      token:
        type: string
      attribute4:
        type: string
      address:
        type: string
  WatchResponse:
    properties:
      kind:
        type: string
      id:
        type: string
      resourceId:
        type: string
      resourceUri:
        type: string
      token:
        type: string
      expiration:
        type: number
        format: float
uses:
  file-lib_raml: data_model_38555d5e1d9995ba31e2be10d92f5155.raml
