#%RAML 1.0 DataType
displayName: Thumbnail
description: Thumbnail for the file. Only accepted on upload and for files that are not already thumbnailed by Google.
properties:
  image:
    type: string
  mimeType:
    type: string
