#%RAML 1.0 DataType
displayName: Owners
description: The owner(s) of a file.
properties:
  kind:
    type: string
  displayName:
    type: string
  isAuthenticatedUser:
    type: boolean
  permissionId:
    type: string
  emailAddress:
    type: string
  picture: "!include data_model_45186b677530f54af97d2eba0346c9d9.raml"
